config/routes.rb
Rails.application.routes.draw do

  get "/", to: 'homes#index'

  resources :users
  resources :user_data_fields
  resources :user_data_groups do
    member do
      post 'add_fields'
      delete '/remove_item/:item_id', to: 'user_data_groups#remove_item', as: :remove_item
    end
  end

  get "/questionnaire", to: 'user_data#index'
  get "/questionnaire/fill", to: 'user_data#show'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_data_values
  has_many :user_data_fields, through: :user_data_values
  accepts_nested_attributes_for :user_data_values, allow_destroy: true

  def as_options
    [self.name, self.id]
  end
end

app/models/user_data_field.rb
class UserDataField < ApplicationRecord
  has_many :user_data_group_items
  has_many :user_data_values
end

app/models/user_data_group.rb
class UserDataGroup < ApplicationRecord
  has_many :user_data_group_items
  has_many :user_data_fields, through: :user_data_group_items

  def user_data_field_ids
    self.user_data_fields.pluck(:id)
  end

  def as_options
    [self.title, self.id]
  end

end

app/models/user_data_group_item.rb
class UserDataGroupItem < ApplicationRecord
  belongs_to :user_data_group
  belongs_to :user_data_field
end

app/models/user_data_value.rb
class UserDataValue < ApplicationRecord
  belongs_to :user_data_field
  belongs_to :user
  after_commit :show_in_profile, on: [:create, :update]

  def show_in_profile
    if self.value && !self.visible
      self.update(visible: true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/user_data_controller.rb
class UserDataController < ApplicationController
  def index
    @users = User.all
    @user_options = @users.map {|u| u.as_options}
    @groups = UserDataGroup.all
    @group_options = @groups.map {|g| g.as_options}
  end

  def show
    user_id = params[:user_id]
    group_id = params[:group_id]
    @group = UserDataGroup.find(group_id)
    field_ids = @group.user_data_field_ids
    @field_values = []
    field_ids.each do |field_id|
      field_val = UserDataValue.find_or_create_by(user_id: user_id, user_data_field_id: field_id)
      if field_val
        @field_values.push(field_val)
      end
    end
    @user = User.find(user_id)
  end
end

app/controllers/user_data_fields_controller.rb
class UserDataFieldsController < ApplicationController

  def index
    @fields = UserDataField.all
  end

  def show
    @field = UserDataField.find(params[:id])
  end

  def new
    @field = UserDataField.new
  end

  def create
    @field = UserDataField.new(field_params)
    if @field.save
      redirect_to @field
    else
      render :new, status: :unprocessable_entity  
    end
  end

  private
  def field_params
    params.require(:user_data_field).permit(:code,:label)
  end

end

app/controllers/user_data_group_items_controller.rb
class UserDataGroupItemsController < ApplicationController
  def destroy
    @item = UserDataGroupItem.find(params[:id])
    @item.destroy
    render json: { message: 'item deleted' }, status: :ok
  end
end

app/controllers/user_data_groups_controller.rb
class UserDataGroupsController < ApplicationController

  def index
    @groups = UserDataGroup.all
  end

  def show
    @group = UserDataGroup.find(params[:id])
    group_field_ids = @group.user_data_field_ids
    @fields = UserDataField.where.not(id: group_field_ids)
  end

  def new
    @group = UserDataGroup.new
  end

  def create
    @group = UserDataGroup.new(group_params)
    if @group.save
      redirect_to @group
    else
      render :new, status: :unprocessable_entity  
    end
  end

  def add_fields
    @group = UserDataGroup.find(params[:id])
    field_ids = params[:field_ids]
    field_ids.each do |f|
      @group.user_data_group_items.create(user_data_field_id: f)
    end
    redirect_back fallback_location: { action: "show", id: params[:id] }
  end

  def remove_item
    @group = UserDataGroup.find(params[:id])
    item_id = params[:item_id]
    @item = UserDataGroupItem.find(item_id)
    if @item.destroy
      redirect_back fallback_location: { action: "show", id: params[:id] }
    else
      render :new, status: :unprocessable_entity
    end
  end

  private
  def group_params
    params.require(:user_data_group).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_back fallback_location: { action: "show", id: @user.id }
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      p "sukses"
      redirect_back fallback_location: { action: "show", id: @user.id }
    else
      p "gagal"
      render :new, status: :unprocessable_entity
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, 
      user_data_values_attributes: ::UserDataValue.attribute_names.map(&:to_sym).push(:_destroy)
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/user_data_fields_helper.rb
module UserDataFieldsHelper
end

app/helpers/user_data_group_items_helper.rb
module UserDataGroupItemsHelper
end

app/helpers/user_data_groups_helper.rb
module UserDataGroupsHelper
end

app/helpers/user_data_helper.rb
module UserDataHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/homes/index.html.erb
<div style="padding: 20px;">
  <h1>EMR Mockup Home</h1>
    <div style="display:flex;flex-direction: column;">
      <%= link_to users_path do %>
        <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px; padding-left: 10px;padding-right: 10px;padding-top: 5px;padding-bottom: 5px;""> Manage User </button>
      <% end %>
      
      <%= link_to user_data_fields_path do %>
        <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px; padding-left: 10px;padding-right: 10px;padding-top: 5px;padding-bottom: 5px;"> Manage Field </button>
      <% end %>
      
      <%= link_to user_data_groups_path do %>
        <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px; padding-left: 10px;padding-right: 10px;padding-top: 5px;padding-bottom: 5px;"> Manage Group </button>
      <% end %>

      <%= link_to questionnaire_path do %>
        <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px; padding-left: 10px;padding-right: 10px;padding-top: 5px;padding-bottom: 5px;"> Fill Questionnaire </button>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EmrMockup</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/user_data/index.html.erb
<div style="padding: 20px;">
  <h1>Fill Questionnaire</h1>
    <a href="/"  style="margin-bottom: 10px;padding: 5px;"><button><- Home</button></a>
    
    <%= form_with url: questionnaire_fill_path, method: :get do %>
      <h3>Select User</h3>
      <%= select_tag "user_id", options_from_collection_for_select(@users, "id", "name") %>
      <br>
      <h3>Select Questionnaire</h3>
      <%= select_tag "group_id", options_from_collection_for_select(@groups, "id", "title") %>
      <br>
      <%= submit_tag "Go Fill",  style:"margin-top: 10px;" %>
    <% end %>
</div>

app/views/user_data/show.html.erb
<div style="padding: 20px;">
  <h1>Fill Questionnaire</h1>
    <a href="/"  style="margin-bottom: 10px;padding: 5px;"><button><- Home</button></a>
    
    <div><h3>Title: <b><%= @group.title %></b></div>

    <div><%= @group.description %></div>

    <%= form_for @user do |f| %>

      <!-- Add more user fields here as needed -->

      <!-- Fields for user_data_valuees -->
      <% @field_values.each do |fv| %>
        <%= f.fields_for :user_data_values, fv do |user_data_value_fields| %>
        <div class="user_data_value-fields">
          <%= user_data_value_fields.label :value, value: fv.user_data_field.label %>
          <%= user_data_value_fields.text_field :value, value: fv.value  %>
        </div>
        <% end %>
      <% end %>
      <div class="actions">
        <%= f.submit "Update Answers" %>
      </div>
    <% end %>

</div>

app/views/user_data_fields/index.html.erb
<div style="padding: 20px;">
  <h1>Fields#index</h1>
  <a href="/"  style="margin-bottom: 10px;padding: 5px;"><button><- Home</button></a>
  
  <div class="main-content">
    <% @fields.each do |field| %>
      <div style="display:flex;flex-direction:row;margin-top:20px;">
        <div><%= field.id %>. <%= field.code %> - <%= field.label %></div>
        <%= link_to user_data_field_path(field), style: "margin-left:10px;" do %>
        <button> See Details </button>
        <%end%>
      </div>
    <% end %>

    <%= link_to new_user_data_field_path do %>
      <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px;"> New Fields </button>
    <% end %>
  </div>
</div>

app/views/user_data_fields/new.html.erb
<div class="form-content" style="padding: 20px;">
  <%= form_with model: @field do |f| %>
    <%= f.text_field :code, placeholder: "Code", required: true %>
    <%= f.text_field :label, placeholder: "Label", required: true %>
    <%= f.submit %>
  <% end %>

  <%= link_to 'Back', user_data_fields_path %>
</div>

app/views/user_data_fields/show.html.erb
<div style="padding: 20px;">
  <h1>User Data Field Show</h1>

  <div class="main-content">
      <div><%= @field.id %>. <%= @field.code %> - <%= @field.label %></div>

    <%= link_to new_user_data_field_path do %>
      <button style="background-color: #0000FF;color: #FFFFFF;"> New Field </button>
    <% end %>

    <%= link_to 'Back', user_data_fields_path %>
  </div>
</div>

app/views/user_data_groups/index.html.erb
<div style="padding: 20px;">
  <h1>Groups#index</h1>
  <a href="/"  style="margin-bottom: 10px;padding: 5px;"><button><- Home</button></a>
  
  <div class="main-content">
    <% @groups.each do |group| %>
      <div style="display:flex;flex-direction:row;margin-top:20px;">
        <div><%= group.id %>. <%= group.title %></div>
        <%= link_to user_data_group_path(group), style: "margin-left:10px;" do %>
          <button> See Details </button>
        <%end%>
      </div>
    <% end %>

  </div>
  <%= link_to new_user_data_group_path do %>
    <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px;"> New Group </button>
  <% end %>
</div>

app/views/user_data_groups/new.html.erb
<div class="form-content" style="padding: 20px;">
  <%= form_with model: @group do |f| %>
    <%= f.text_field :title, placeholder: "Title", required: true %>
    <%= f.text_area :description, placeholder: "Description", required: true %>
    <%= f.submit %>
  <% end %>

  <%= link_to 'Back', user_data_groups_path %>
</div>

app/views/user_data_groups/show.html.erb
<div style="padding: 20px;">
  <h1>User Data Group Show</h1>

  <div class="main-content">
    <div><h3>Title: <b><%= @group.title %></b></div>

    <div><%= @group.description %></div>

    <div class="fields-area">
      <h2>Current Fields</h2>
      <% @group.user_data_group_items.each do |gfield| %>
        <div style="display:flex;flex-direction:row;margin-top:20px;margin-bottom:20px;">
          <div><%= gfield.user_data_field.id %>. <%= gfield.user_data_field.label %></div>
          <div style="margin-left:10px;">
            <%= form_with url: remove_item_user_data_group_path(id:@group.id, item_id: gfield.id), method: :delete do %>
              <%= submit_tag "Delete", style: "background-color: #FF0000;color:#FFFFFF;" %>
            <% end %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="fields-area" style="margin-top:20px;margin-bottom:20px;">
      <div><h3>INPUT AREA</h3></div>
      <%= form_with url: add_fields_user_data_group_path(@group.id) do %>
        <% @fields.each do |field| %>
          <div style="margin-top:10px;margin-bottom:10px;display:flex;flex-direction:row;">
            <div style="margin-right: 15px;">
              <%= check_box_tag "field_ids[]", field.id, @group.user_data_field_ids.include?(field.id) %>
            </div>
            <div>
              <div>Code: <%=h field.code %><br /></div>
              <div>Question: <%=h field.label %><br /></div>
            </div>
          </div>
        <% end %>
        <%= submit_tag "Add Fields", style: "margin-top:20px;margin-bottom:20px;" %>
      <% end %>
    </div>

    <%= link_to 'Back', user_data_groups_path %>
  </div>
</div>

app/views/users/index.html.erb
<div style="padding: 20px;">
  <h1>User List</h1>
  <a href="/"  style="margin-bottom: 10px;padding: 5px;"><button><- Home</button></a>

  <div class="main-content">
    <% @users.each do |user| %>
      <div style="display:flex;flex-direction:row;margin-top:20px;">
        <div><%= user.id %>. <%= user.name %></div>
        <%= link_to user_path(user), style: "margin-left:10px;" do %>
          <button> See Details </button>
        <%end%>
      </div>
    <% end %>
  </div>
  <%= link_to new_user_path do %>
    <button style="background-color: #0000FF;color: #FFFFFF; margin-top:20px;"> New User </button>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="form-content" style="padding: 20px;">
  <%= form_with model: @user do |f| %>
    <div style="display:flex;flex-direction: column;">
      <%= f.text_field :name, placeholder: "Name", required: true %>
      <%= f.submit %>
    </div>
  <% end %>

  <%= link_to 'Back', users_path %>
</div>

app/views/users/show.html.erb
<div style="padding: 20px;">
  <h1>UserShow</h1>

  <div class="main-content">
    <div style="margin-bottom:30px;"><%= @user.id %>. <%= @user.name %></div>

    <% @user.user_data_values.each do |data|%>
      <% if data.visible %>
        <div style="margin-bottom:10px;">
          <div><%= data.user_data_field.code %></div>
          <div><%= data.value %></div>
        </div>
      <% end%>
    <% end %>

    <%= link_to new_user_path do %>
      <button style="background-color: #0000FF;color: #FFFFFF;margin-top:80px;"> New User </button>
    <% end %>

    <%= link_to 'Back', users_path %>
  </div>
</div>